[package]
name = "node_system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The only reason this has macroquad, is for Vec2
macroquad = "0.3.15"